package docker

// Making an ordinary compose file run behind Traefik.
//
// A compose file written to run on its own is self-contained: it puts its own
// nginx in front, binds host port 80, and knows nothing of a reverse proxy.
// Here Traefik owns 80 and 443 for every application on the server and reaches
// services over a Docker network instead, so that same file cannot start — and
// the edits it needs are always the same three: drop the host bindings Traefik
// already holds, join the external network, and carry the router labels that
// make the site reachable. Done by hand they are easy to get subtly wrong, and
// nothing says so until a deploy half-succeeds.
//
// So Quasar makes them itself, into a generated file beside the original. The
// repository keeps the file its author wrote — it is still what runs on a
// laptop — and what actually ran on the server is readable on disk next to it.

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"quasar/internal/db"

	"gopkg.in/yaml.v3"
)

// adaptedComposeFile is the generated file's name, in the same directory as the
// compose file it was made from so every relative path in it — build contexts,
// bind mounts — still resolves to the same place.
const adaptedComposeFile = "docker-compose.quasar.yml"

// adaptedHeader is prepended to the generated file. Whoever finds it on the
// server needs to know it is not the file to edit.
const adaptedHeader = `# Generated by Quasar from %s — do not edit.
#
# It is rewritten from that file on every deploy, so changes made here are lost.
# Quasar dropped the host port bindings Traefik already holds, put the service
# serving the site on the %s network, and gave it the router labels.
`

// ComposeAdaptation is what Quasar made of an application's compose file: the
// service it pointed Traefik at, and what it changed to get there.
//
// It is recomputed from the file rather than stored, so it always describes the
// file as it is now — a repository that moved its front end to another service
// says so on the next page load, not on the next deploy.
type ComposeAdaptation struct {
	Services    []string // every service in the file, in the order written
	Service     string   // the service Traefik is pointed at, "" when undecided
	Port        int      // the container port Traefik is pointed at
	Unpublished []string // host bindings dropped, as "nginx 80:80"
	// Published are the host bindings left in place, as "backend 8080:8080".
	// They are not Quasar's to remove — a stack may publish a database or a
	// game server on purpose — but they bypass Traefik, and therefore TLS and
	// every protection configured for the app, so the page names them.
	Published []string
	Choice    string // the service the operator picked, "" for automatic
	// Author is a file that already carries Traefik labels: its author has
	// done this themselves, and Quasar changes nothing.
	Author bool
	// Ambiguous is a file with several services and nothing to single one out.
	// Nothing is changed, because guessing which one serves the site would
	// route the domain at a database as readily as at a web server.
	Ambiguous bool
	// Gone is a picked service the file no longer has.
	Gone bool
	// Err is why the file could not be read as compose, when it could not.
	Err string
}

// Adapted reports whether Quasar rewrote the file.
func (a ComposeAdaptation) Adapted() bool { return a.Service != "" && !a.Author }

// adaptOptions is everything outside the compose file the adaptation needs.
type adaptOptions struct {
	Network string // the external network Traefik watches
	Choice  string // the service the operator picked, "" to work it out
	Port    int    // the port configured for the app, preferred over a guess
	// Labels builds the Traefik labels for the routed service, given the
	// container port the adaptation settled on. It is a function because that
	// port is only known once the file has been read.
	Labels func(port int) map[string]string
}

// adaptCompose rewrites a compose file to run behind Traefik and reports what
// it did. The returned bytes are nil whenever nothing was changed — an already
// adapted file, an undecidable one — and the caller runs the original.
func adaptCompose(src []byte, opt adaptOptions) ([]byte, ComposeAdaptation, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return nil, ComposeAdaptation{Err: err.Error()}, err
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		err := fmt.Errorf("the compose file is not a mapping")
		return nil, ComposeAdaptation{Err: err.Error()}, err
	}
	root := doc.Content[0]

	servicesNode := mapValue(root, "services")
	if servicesNode == nil || servicesNode.Kind != yaml.MappingNode {
		err := fmt.Errorf("the compose file declares no services")
		return nil, ComposeAdaptation{Err: err.Error()}, err
	}

	services := readServices(servicesNode)
	rep := ComposeAdaptation{Choice: opt.Choice}
	for _, s := range services {
		rep.Services = append(rep.Services, s.name)
		if s.hasTraefikLabels() {
			rep.Author = true
		}
	}
	// A file whose author wired it to Traefik themselves is left exactly as it
	// is: they know which service serves what, and a second router pointed at
	// another service would fight the one they wrote.
	if rep.Author {
		for _, s := range services {
			if s.hasTraefikLabels() {
				rep.Service = s.name
				break
			}
		}
		return nil, rep, nil
	}

	web := pickWebService(services, opt.Choice, opt.Port)
	if web == nil {
		rep.Gone = opt.Choice != ""
		rep.Ambiguous = opt.Choice == ""
		return nil, rep, nil
	}
	rep.Service = web.name
	rep.Port = web.routedPort(opt.Port)

	// Every service is stripped, not just the routed one: whichever of them
	// binds 80 is what stops the stack from starting.
	for _, s := range services {
		for _, text := range s.unpublishEdgePorts() {
			rep.Unpublished = append(rep.Unpublished, s.name+" "+text)
		}
		for _, p := range s.ports {
			if p.hostLo > 0 && !p.bindsEdge() {
				rep.Published = append(rep.Published, s.name+" "+p.text)
			}
		}
	}

	setLabels(web.node, opt.Labels(rep.Port))
	joinNetwork(web.node, opt.Network)
	declareExternalNetwork(root, opt.Network)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, rep, err
	}
	if err := enc.Close(); err != nil {
		return nil, rep, err
	}
	return buf.Bytes(), rep, nil
}

// composeContext returns the directory docker compose runs in and the file it
// is actually run with: the adapted file when the last deploy wrote one, and
// otherwise the operator's own. Every compose command goes through this —
// logs, exec, stop — so they all act on the stack that is really running.
func (c *Client) composeContext(a *db.App) (dir, file string) {
	dir, file = c.composeSource(a)
	if file == "" {
		return dir, ""
	}
	if adapted := filepath.Join(dir, adaptedComposeFile); fileExists(adapted) {
		return dir, adapted
	}
	return dir, file
}

// adaptOptionsFor is how an app's own configuration reaches the adaptation:
// the domain and protections it is routed with, and the service its operator
// picked when Quasar could not work one out.
func (c *Client) adaptOptionsFor(a *db.App) adaptOptions {
	return adaptOptions{
		Network: c.network,
		Choice:  a.ComposeService,
		Port:    a.Port,
		Labels: func(port int) map[string]string {
			labels := c.traefikLabelsPort(a, port)
			// The label marking a single-container app is deliberately not
			// carried into a stack: it is what tells the two kinds of
			// deployment apart, and a stack's containers belong to its compose
			// project, not to Quasar.
			delete(labels, appLabel)
			return labels
		},
	}
}

// writeAdaptedCompose regenerates the file the stack is deployed from, and is
// called before every compose deploy so the file follows the app: a renamed
// domain, a new basic-auth password and a `git pull` all land in it.
//
// When there is nothing to adapt it removes the file instead. A generated file
// outliving the reason it was generated is worse than none: compose would keep
// running it, and the compose file the operator is looking at would no longer
// be the one in effect.
func (c *Client) writeAdaptedCompose(a *db.App) error {
	dir, src := c.composeSource(a)
	if src == "" {
		return nil // composeCmd reports an app with no compose file
	}
	out := filepath.Join(dir, adaptedComposeFile)
	raw, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("read compose file: %w", err)
	}
	body, rep, err := adaptCompose(raw, c.adaptOptionsFor(a))
	if err != nil || !rep.Adapted() {
		// A file that cannot be parsed is not this function's to report: `up`
		// fails on it straight away and says where, in compose's own words.
		os.Remove(out)
		return nil
	}
	header := fmt.Sprintf(adaptedHeader, filepath.Base(src), c.network)
	return os.WriteFile(out, append([]byte(header), body...), 0o644)
}

// ComposeAdaptationFor reports how a stack's compose file is deployed: which
// service answers for the domain, on which port, and what Quasar had to change.
// It reads the file every time rather than remembering the last deploy, so the
// page describes the file as it stands now.
func (c *Client) ComposeAdaptationFor(a *db.App) ComposeAdaptation {
	if !c.UsesCompose(a) {
		return ComposeAdaptation{}
	}
	_, src := c.composeSource(a)
	if src == "" {
		return ComposeAdaptation{}
	}
	raw, err := os.ReadFile(src)
	if err != nil {
		return ComposeAdaptation{Err: "the compose file could not be read"}
	}
	_, rep, _ := adaptCompose(raw, c.adaptOptionsFor(a))
	return rep
}

func fileExists(path string) bool {
	st, err := os.Stat(path)
	return err == nil && !st.IsDir()
}

// composeService is one service of the file, with its ports already read.
type composeService struct {
	name  string
	node  *yaml.Node
	ports []composePort
}

// composePort is one entry of a service's ports list, in either of the two
// syntaxes compose accepts.
type composePort struct {
	hostLo, hostHi int    // the host ports it binds, 0 when it binds none
	container      string // the container port, as written
	text           string // the entry as written, for the report
}

func readServices(servicesNode *yaml.Node) []composeService {
	var out []composeService
	for i := 0; i+1 < len(servicesNode.Content); i += 2 {
		name := servicesNode.Content[i].Value
		node := detachAlias(servicesNode, i+1)
		if node.Kind != yaml.MappingNode {
			continue
		}
		expandMerges(node, 0)
		s := composeService{name: name, node: node}
		if ports := mapValue(node, "ports"); ports != nil && ports.Kind == yaml.SequenceNode {
			for _, entry := range ports.Content {
				s.ports = append(s.ports, parsePortEntry(entry))
			}
		}
		out = append(out, s)
	}
	return out
}

// A compose file is free to write a service as an alias of an anchor
// (`web: *base`) or to pull keys into it with a merge key (`<<: *defaults`),
// and plenty do. Both have to be flattened before the service is read or
// written: read as they stand, such a service looks like it declares no ports
// at all, and written into as they stand, the Traefik labels would land on the
// anchor and reach every other service sharing it — Traefik would then see
// several containers claiming one domain.
//
// Flattening only touches files that use these, so an ordinary file comes back
// out exactly as it went in.

// detachAlias replaces an aliased value with a copy of what it points at, and
// returns the node to work with. The copy is what makes writing to it safe.
func detachAlias(parent *yaml.Node, idx int) *yaml.Node {
	node := parent.Content[idx]
	if node.Kind != yaml.AliasNode {
		return node
	}
	copied := copyNode(resolveAlias(node))
	parent.Content[idx] = copied
	return copied
}

// resolveAlias follows an alias to the node it stands for.
func resolveAlias(n *yaml.Node) *yaml.Node {
	for i := 0; n != nil && n.Kind == yaml.AliasNode && i < mergeDepth; i++ {
		n = n.Alias
	}
	return n
}

// mergeDepth bounds how far anchors are followed into one another, so a file
// that manages to make them circular cannot hang a deploy.
const mergeDepth = 8

// copyNode deep-copies a node, dropping the anchor name: the copy stands on
// its own, and two definitions of one anchor would be a broken file.
func copyNode(n *yaml.Node) *yaml.Node {
	if n == nil {
		return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	}
	out := *n
	out.Anchor = ""
	out.Content = make([]*yaml.Node, len(n.Content))
	for i, child := range n.Content {
		out.Content[i] = copyNode(resolveAlias(child))
	}
	return &out
}

// expandMerges writes a mapping's merge keys out into the mapping itself, so
// what it inherits is visible where the rest of this file looks for it. Keys
// the mapping states itself win, and among several merged sources the first
// wins, which is what the merge key means.
func expandMerges(m *yaml.Node, depth int) {
	if m == nil || m.Kind != yaml.MappingNode || depth >= mergeDepth {
		return
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value != "<<" {
			continue
		}
		sources := m.Content[i+1]
		m.Content = append(m.Content[:i], m.Content[i+2:]...)
		if sources.Kind != yaml.SequenceNode {
			sources = &yaml.Node{Kind: yaml.SequenceNode, Content: []*yaml.Node{sources}}
		}
		for _, source := range sources.Content {
			// Copied before expanding, or expanding one anchor would rewrite it
			// for every other mapping merging the same one.
			merged := copyNode(resolveAlias(source))
			expandMerges(merged, depth+1)
			if merged.Kind != yaml.MappingNode {
				continue
			}
			for j := 0; j+1 < len(merged.Content); j += 2 {
				if mapValue(m, merged.Content[j].Value) == nil {
					m.Content = append(m.Content, merged.Content[j], merged.Content[j+1])
				}
			}
		}
		// A mapping may carry more than one merge key, and what was just
		// merged in may carry its own.
		expandMerges(m, depth+1)
		return
	}
}

// parsePortEntry reads one ports entry: the short string form
// ("127.0.0.1:8080:80/tcp") or the long mapping form.
func parsePortEntry(n *yaml.Node) composePort {
	switch n.Kind {
	case yaml.ScalarNode:
		s := n.Value
		if i := strings.IndexByte(s, '/'); i >= 0 {
			s = s[:i]
		}
		parts := strings.Split(s, ":")
		p := composePort{container: parts[len(parts)-1], text: n.Value}
		// One part is a container port compose publishes on some host port it
		// picks itself, which can never be 80 — hence only two parts or more.
		if len(parts) >= 2 {
			p.hostLo, p.hostHi = publishedRange(parts[len(parts)-2])
		}
		return p
	case yaml.MappingNode:
		p := composePort{}
		if t := mapValue(n, "target"); t != nil {
			p.container = t.Value
		}
		published := ""
		if v := mapValue(n, "published"); v != nil {
			published = v.Value
		}
		p.hostLo, p.hostHi = publishedRange(published)
		if p.text = published + ":" + p.container; published == "" {
			p.text = p.container
		}
		return p
	}
	return composePort{}
}

// bindsEdge reports an entry claiming one of the host ports Traefik holds.
func (p composePort) bindsEdge() bool {
	if p.hostLo == 0 {
		return false
	}
	for _, e := range edgePorts {
		if e.Port >= p.hostLo && e.Port <= p.hostHi {
			return true
		}
	}
	return false
}

func (s composeService) hasTraefikLabels() bool {
	labels := mapValue(s.node, "labels")
	if labels == nil {
		return false
	}
	// Compose takes labels as a mapping or as a list of "key=value" strings,
	// and both spellings are common in the wild.
	for _, n := range labels.Content {
		if strings.HasPrefix(n.Value, "traefik.") {
			return true
		}
	}
	return false
}

// bindsEdge reports a service claiming a host port Traefik holds, which in a
// self-contained stack is what marks its front door.
func (s composeService) bindsEdge() bool {
	for _, p := range s.ports {
		if p.bindsEdge() {
			return true
		}
	}
	return false
}

// declares reports whether the service offers the given container port, either
// published or merely exposed.
func (s composeService) declares(port int) bool {
	for _, p := range s.containerPorts() {
		if p == port {
			return true
		}
	}
	return false
}

// containerPorts lists the ports the service says it listens on, in the order
// written: those in its ports entries first, then its expose entries.
func (s composeService) containerPorts() []int {
	var out []int
	add := func(text string) {
		if n, err := strconv.Atoi(strings.TrimSpace(text)); err == nil && n > 0 {
			out = append(out, n)
		}
	}
	for _, p := range s.ports {
		add(p.container)
	}
	if exposed := mapValue(s.node, "expose"); exposed != nil {
		for _, n := range exposed.Content {
			add(n.Value)
		}
	}
	return out
}

// routedPort is the container port Traefik is pointed at. The port configured
// for the app wins whenever the service actually offers it — that is the one
// the operator can see in the dashboard — and otherwise the service is taken at
// its word, since routing to a port nothing listens on only produces 502s.
func (s composeService) routedPort(appPort int) int {
	declared := s.containerPorts()
	if len(declared) == 0 || s.declares(appPort) {
		return appPort
	}
	// A stack's front door usually publishes 80 to the host and serves on 80
	// inside, so the entry that collided with Traefik names the right port.
	for _, p := range s.ports {
		if p.bindsEdge() {
			if n, err := strconv.Atoi(p.container); err == nil && n > 0 {
				return n
			}
		}
	}
	return declared[0]
}

// unpublishEdgePorts drops the entries binding a host port Traefik holds and
// keeps the container port reachable as an expose entry. It returns the
// dropped entries as written.
func (s composeService) unpublishEdgePorts() []string {
	ports := mapValue(s.node, "ports")
	if ports == nil || ports.Kind != yaml.SequenceNode {
		return nil
	}
	var dropped []string
	kept := ports.Content[:0]
	for i, entry := range ports.Content {
		if i < len(s.ports) && s.ports[i].bindsEdge() {
			dropped = append(dropped, s.ports[i].text)
			addExpose(s.node, s.ports[i].container)
			continue
		}
		kept = append(kept, entry)
	}
	ports.Content = kept
	// An empty ports list is valid but reads as an oversight; the service
	// publishes nothing now, so the key itself goes.
	if len(ports.Content) == 0 {
		mapDelete(s.node, "ports")
	}
	return dropped
}

// addExpose records a container port on the service's expose list, creating it
// if needed. It documents the port for anyone reading the file; reachability
// over the network comes from the shared network, not from this.
func addExpose(svc *yaml.Node, port string) {
	if port == "" {
		return
	}
	exposed := mapValue(svc, "expose")
	if exposed == nil {
		exposed = &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		mapSet(svc, "expose", exposed)
	}
	if exposed.Kind != yaml.SequenceNode {
		return
	}
	for _, n := range exposed.Content {
		if n.Value == port {
			return
		}
	}
	exposed.Content = append(exposed.Content, quoted(port))
}

// pickWebService decides which service the domain is routed to, and returns nil
// when it cannot be decided. An explicit choice is honoured whenever the file
// still has that service.
func pickWebService(services []composeService, choice string, appPort int) *composeService {
	if choice != "" {
		for i := range services {
			if services[i].name == choice {
				return &services[i]
			}
		}
		return nil
	}
	// The service binding the host's HTTP port is the stack's own front door:
	// on a laptop it is what the browser talks to, so it is what Traefik should
	// talk to here.
	if only := single(services, func(s composeService) bool { return s.bindsEdge() }); only != nil {
		return only
	}
	// Failing that, the shape of the stack itself — which is all there is to go
	// on for the many compose files that publish nothing at all.
	if front := frontOfGraph(services); front != nil {
		return front
	}
	// Failing that, the one offering the port the app is configured with.
	if only := single(services, func(s composeService) bool { return s.declares(appPort) }); only != nil {
		return only
	}
	if len(services) == 1 {
		return &services[0]
	}
	return nil
}

// frontOfGraph returns the service the stack is built around: the one that
// waits for others and that nothing waits for. A stack is a stack because
// something fronts it, and depends_on is where its author wrote down what
// fronts what — no image name, no service name, no port needed.
//
// It is only trusted when every service takes part in that graph, because a
// service standing outside it is a service the graph does not describe: a lone
// web server beside a worker that depends on a queue would otherwise hand the
// domain to the worker.
func frontOfGraph(services []composeService) *composeService {
	awaited := map[string]bool{}
	for _, s := range services {
		for _, name := range s.dependsOn() {
			awaited[name] = true
		}
	}
	var front *composeService
	for i := range services {
		s := &services[i]
		waits := len(s.dependsOn()) > 0
		switch {
		case !waits && !awaited[s.name]:
			return nil // outside the graph, so the graph does not describe the stack
		case waits && !awaited[s.name]:
			if front != nil {
				return nil // two front doors, and no way to tell them apart
			}
			front = s
		}
	}
	return front
}

// dependsOn lists the services this one waits for, in either spelling compose
// accepts: a list of names, or a mapping of name to the condition waited on.
func (s composeService) dependsOn() []string {
	dep := mapValue(s.node, "depends_on")
	if dep == nil {
		return nil
	}
	var out []string
	switch dep.Kind {
	case yaml.SequenceNode:
		for _, n := range dep.Content {
			out = append(out, n.Value)
		}
	case yaml.MappingNode:
		for i := 0; i+1 < len(dep.Content); i += 2 {
			out = append(out, dep.Content[i].Value)
		}
	}
	return out
}

// single returns the one service matching, or nil when none or several do.
func single(services []composeService, match func(composeService) bool) *composeService {
	var found *composeService
	for i := range services {
		if !match(services[i]) {
			continue
		}
		if found != nil {
			return nil
		}
		found = &services[i]
	}
	return found
}

// setLabels merges the Traefik labels into whatever the service already
// carries, in either of the two spellings compose accepts.
func setLabels(svc *yaml.Node, labels map[string]string) {
	existing := mapValue(svc, "labels")
	if existing == nil {
		existing = &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		mapSet(svc, "labels", existing)
	}
	for _, key := range sortedKeys(labels) {
		value := escapeInterpolation(labels[key])
		switch existing.Kind {
		case yaml.MappingNode:
			mapSet(existing, key, quoted(value))
		case yaml.SequenceNode:
			existing.Content = append(existing.Content, quoted(key+"="+value))
		}
	}
}

// escapeInterpolation doubles every "$" so that compose passes the value on as
// written instead of reading it as a variable reference.
//
// A bcrypt hash is why this exists. "$2a$10$KI2SuB..." reaches the container as
// "$2a$10.6c4e..." — compose substituted the undefined variable $KI2SuB for
// nothing — and Traefik then rejects every password against the truncated hash,
// so a protected stack asks for credentials it can never accept. Only the
// labels Quasar generates are escaped: the rest of the file is the author's,
// and compose interpolates it exactly as it would were they running it
// themselves.
func escapeInterpolation(v string) string { return strings.ReplaceAll(v, "$", "$$") }

// joinNetwork puts the service on the external network Traefik watches.
func joinNetwork(svc *yaml.Node, network string) {
	nets := mapValue(svc, "networks")
	if nets == nil {
		// Naming a network at all opts the service out of the default one, so
		// the default has to be named too or the service loses every other
		// service in its own stack.
		mapSet(svc, "networks", &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq",
			Content: []*yaml.Node{plain("default"), plain(network)}})
		return
	}
	switch nets.Kind {
	case yaml.SequenceNode:
		for _, n := range nets.Content {
			if n.Value == network {
				return
			}
		}
		nets.Content = append(nets.Content, plain(network))
	case yaml.MappingNode:
		if mapValue(nets, network) == nil {
			mapSet(nets, network, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null", Value: ""})
		}
	}
}

// declareExternalNetwork adds the top-level declaration that says the Traefik
// network is one Quasar already created, rather than one for this stack.
func declareExternalNetwork(root *yaml.Node, network string) {
	nets := mapValue(root, "networks")
	if nets == nil {
		nets = &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		mapSet(root, "networks", nets)
	}
	if nets.Kind != yaml.MappingNode || mapValue(nets, network) != nil {
		return
	}
	external := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	mapSet(external, "external", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
	mapSet(nets, network, external)
}

// mapValue returns the value for a key of a YAML mapping, or nil.
func mapValue(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}

// mapSet writes a key of a YAML mapping, replacing it in place when it is
// already there so the file keeps the order its author gave it.
func mapSet(n *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			n.Content[i+1] = value
			return
		}
	}
	n.Content = append(n.Content, plain(key), value)
}

func mapDelete(n *yaml.Node, key string) {
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			n.Content = append(n.Content[:i], n.Content[i+2:]...)
			return
		}
	}
}

// plain is a scalar the encoder is free to write unquoted.
func plain(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v}
}

// quoted is a scalar forced to stay a string. Docker label values and port
// numbers are strings, and "true" or "80" left bare would come back as a
// boolean and an integer.
func quoted(v string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: v, Style: yaml.DoubleQuotedStyle}
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	// Sorted so two deploys of an unchanged file produce an identical file.
	sort.Strings(out)
	return out
}
